[auth]
site_url = "https://delightful-daffodil-1fcd87.netlify.app"
additional_redirect_urls = ["https://delightful-daffodil-1fcd87.netlify.app/*"]

[auth.email]
enable_signup = true
enable_confirmations = true
double_confirm_changes = false
enable_email_passwords = true
allowed_email_domains = ["*"]

[auth.external]
enable_email_signup = true
enable_email_autoconfirm = true

[auth.jwt]
enable_jwt = true